### ISSUE TITLE
GUI : some troubles on Ubuntu 15

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#1366]
Running the latest git version of Gama (commit 709ef5df20b46a979c61160ccfaeb5ee4d228b0b), on Ubuntu 15.04 x64 / Java 1.8 / Eclipse Mars SR1, here are some problems :

## True/False switch buttons  
  * When False is selected :  
    ![capture du 2016-01-03 14 25 49](https://cloud.githubusercontent.com/assets/807703/12078944/4158f024-b226-11e5-90e2-c03dd2c3dd65.png)
  * When True is selected :  
    ![capture du 2016-01-03 14 29 55](https://cloud.githubusercontent.com/assets/807703/12078952/7a56bcb2-b226-11e5-98b1-fbc645a24304.png)

==> False position should be corrected

## Monitors not displayed
This one is pretty strange, only the first monitor label / frame / slides is displayed :
![capture du 2016-01-03 14 31 43](https://cloud.githubusercontent.com/assets/807703/12078960/be9cfcc4-b226-11e5-832c-a28ed0423074.png)

  * I can still edit/unfold them, but this doesnt add their frame/labels or whatever :  
![capture du 2016-01-03 14 32 52](https://cloud.githubusercontent.com/assets/807703/12078963/e5806394-b226-11e5-9b84-92f51d938e46.png)

## Display not correctly redrawn :  
  For example when zooming on a map, that should like like this :  
![capture du 2016-01-03 14 34 46](https://cloud.githubusercontent.com/assets/807703/12078965/2f3b611e-b227-11e5-86ae-9d3de8a794d5.png)

  Here's what I get :  
![capture du 2016-01-03 14 34 58](https://cloud.githubusercontent.com/assets/807703/12078967/3dba4638-b227-11e5-945c-c152c206b40b.png)

Here's the code to produce this map  :

    display "Carte" {
        species Paroisses transparency: 0.9 ;
        species Zones_Prelevement transparency: 0.9;
        agents "Eglises Paroissiales" value: Eglises where (each.eglise_paroissiale) aspect: base transparency: 0.5;
        species Chateaux aspect: base ;
        species Foyers_Paysans transparency: 0.5;
        species Agregats transparency: 0.3;
        
        text string(Annee) size: 10000 position: {0, 1} color: rgb("black");
    }

Although it might have some artistical value, I'm not sure that's what targeted :)

**Comment by AlexisDrogoul** [comment]
The artistic value is undeniable — but I agree it is not intentional. This part of the issue is clearly related to #1354. 

Regarding the two other ones, it's clearly intriguing as I've never seen this before on Windows/MacOS or even older versions of Ubuntu. 

Thanks in any case to report these UI problems on Ubuntu, as we have very few people using this OS and willing to test GAMA !

Cheers
Alexis

**Comment by AlexisDrogoul** [comment]
I've just committed what might be a fix for the last  issue. Can you try it ?

**Comment by AlexisDrogoul** [comment]
I still cannot reproduce the bug on monitors. Can anyone (@gama-platform/committers) with Ubuntu try it on a small model ?

**Comment by RCura** [comment]
Running ubuntu 15.04 with java 8.

Still the same issue.
Test model :

    /**
    * Name: MonitorsBug
    * Author: robin
    */

    model MonitorsBug

    global {
        init { create A number: 10; }
        reflex step { create A number: rnd(0,5); }
    }

    entities {
        species A;
    }

    experiment GUI type: gui{
        output {
            monitor "First" value: length(A);
            monitor "Second" value: rnd(0,10);
            monitor "Third" value: rnd(0,100);
        }
    }


Output :

![capture du 2016-01-27 14 20 27](https://cloud.githubusercontent.com/assets/807703/12614581/21b136d0-c501-11e5-87db-9dac1f70b572.png)

But we can still view the content of the other monitors by clicking where the arrow should be :
![capture du 2016-01-27 14 21 38](https://cloud.githubusercontent.com/assets/807703/12614633/714fc2ce-c501-11e5-9818-db3d9fed7ca9.png)


Note that same bug appears when adding a new monitor from the interface :

![capture du 2016-01-27 14 22 19](https://cloud.githubusercontent.com/assets/807703/12614620/629667b0-c501-11e5-941c-f864bf49eab6.png)

**Comment by AlexisDrogoul** [comment]
Very strange. And there are no outputs anywhere (in the console, etc.) ?

**Comment by RCura** [comment]
The monitors are there, but it seems that it's their appearance that doesn't fit.

Just realised I have the same problem with the gama preferences :

![capture du 2016-01-27 18 14 12](https://cloud.githubusercontent.com/assets/807703/12621669/e1eeb952-c521-11e5-930c-03ddb061598c.png)

But for the preferences, if I change the size of this window (even with a minimal change), the preferences do appear as they should :

![capture du 2016-01-27 18 15 38](https://cloud.githubusercontent.com/assets/807703/12621691/05451dc4-c522-11e5-9ddc-eae4f262be89.png)

This doesn't work for the monitor panel though : I can try to increase/decrease it's height and width, but still changes nothing : only the first element is displayed

**Comment by RCura** [comment]
Still the same problems with the current beta release.

**Comment by AlexisDrogoul** [comment]
Yes. That's normal. I havent changed a thing in the monitors so far, trying to understand where this bug comes from. Thinking about it, the fact that it works by resizing the preferences view might be an indication about a wrong size/resize event that prevents monitors from sizing themselves correctly.

**Comment by AlexisDrogoul** [comment]
Hi, 

I close this "general" issue in favor of more focused ones ( #1622 , #1621 , #1619 , #1620 ) that have just been tested on Ubuntu 14 (basically, they are the same as yours).

Cheers
Alexis
