### ISSUE TITLE
jdbc driver

### ISSUE THREAD

**Issue by henane** [gama-platform/gama#1525]
Hi 
I used GAMA 1.5. Now, i have migrated to GAMA 1.7 , the problem arises when accessing to  database. The error:
SQLSkill.select_QM: SQLConnection.selectDB: java.lang.ClassNotFoundException: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver cannot be found by msi.gama.core_1.6.1.qualifier
Any help to fix this error

**Comment by AlexisDrogoul** [comment]
I've pushed a commit which should (I hope) fix this bug. However, it is only available in the developer (Git) version. In case you can run it, can you test it ? Otherwise, we'll try to issue a new beta release later this week. 

Sorry for the inconvenience.

Alexis

**Comment by mrouan** [comment]
Thank you Alexis, 

I have just installed the git version and try my model and still have an error 
2 occurrences in 2 agents at cycle 0: SQLConnection.selectDB: java.lang.ClassNotFoundException: java.lang.ClassNotFoundException: org.postgresql.Driver cannot be found by msi.gama.core_1.7.0.qualifier
any idea ?

Mathias

**Comment by AlexisDrogoul** [comment]
Hi,

Sorry again. I've made another attempt in the latest commit -- a bit as a guess, as the dependencies are not explicitly stated in GeoTools.

Cheers
Alexis

**Comment by mrouan** [comment]
Hi Alexis,
This seems to work for the connection now !
A new problem emerged with postgis but my colleague Celine Lecoq will explain it in another issue...
Thank you

**Comment by AlexisDrogoul** [comment]
Good to know it's working new. The new issue is #1654
