### ISSUE TITLE
Multiple errors when executing several models in headless

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1821]
I struggle to run all the experiments of the model library from the headless module, and I get thousands of errors, maybe I just miss something, but I don't know what...

Example of error I got : 
- While compiling the models "Unit Test", impossible to find the statement "assert".
- While executing "OSM Loading", I got a NoClassDefFoundError (org/apache/commons/compress/compressors/bzip2/BZip2CompressorOutputStream)
- While executing "Raster Image and shapefile Import", I got a OutOfMemoryError
- While executing "comodel_Flood_Evacuation", I got weird combinaisons of the relative paths which leads to an error
- ...

To reproduce this error, change the flag "buildModelLibrary" in Application to true, and change the 2 paths "wikiFolder" and "sourceFolder" in "modelLibraryGenerator". To ignore a folder, add it to the "listNoScreenshot" list.

**Comment by AlexisDrogoul** [comment]
It remains to be seen what plugins the headless application is really loading... At least the two first ones are probably related to the fact that it is not loading all the plugins/libraries present in the release.

**Comment by AlexisDrogoul** [comment]
@gnoubi, any news on this one ? It is quite critical as, now, only a small half of the models can be run in headless. Where are the dependencies defined ? Only in the plugin ? Or do you scan things by hand ?

**Comment by gnoubi** [comment]
Hi 

I am working on the problem. Gama camp introduce bug on headless dependencies. I understand why headless throws error when It is started by eclipse. I don t know why it does not start by command line right now... 

I am focusing on that

Nicolas

Envoyé de mon iPhone

**Comment by gnoubi** [comment]
the problem is solved in the last version of gama

**Comment by benoitgaudou** [comment]
Note that, now, these issues can be tested using the following arguments (in particular the -check):
-v -m 8000m -check PATH_TO_GAMA_SOURCE PATH_TO_WIKI PATH_TO_AN_EXISTING_OUTPUT_FILE

**Comment by benoitgaudou** [comment]
Some errors still appear. In particular about the co-modeling models : 

..Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/models/Ants Adapter.gaml
.Experimentator agent running comodel_mix_behaviors_model(0)
java.lang.NullPointerException
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:469)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:424)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Runtime error: Java error: nil value detected
Exception in thread "Thread-35" Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:63)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:439)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Caused by: java.lang.NullPointerException
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:469)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:424)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	... 12 more
Experimentator agent running Simple(0)
..
Simulation duration: 3094ms

Simulation duration: 7445ms
....Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/models/Ants Adapter.gaml
.Experimentator agent running Complete(0)
..............Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/models/Ants Adapter.gaml
..Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/models/Prey Predator Adapter.gaml
.java.lang.NullPointerException
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:469)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:424)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Runtime error: Java error: nil value detected
Exception in thread "Thread-36" Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:63)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:439)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Caused by: java.lang.NullPointerException
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:469)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:424)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	... 12 more
....................
Simulation duration: 1580ms

Simulation duration: 1115ms
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/models/Prey Predator Adapter.gaml
...Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/models/Prey Predator.gaml
...
Simulation duration: 1037ms
.
Simulation duration: 3938ms
java.lang.NullPointerException
Runtime error: Java error: nil value detected
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:469)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:424)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Exception in thread "Thread-40" Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:63)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:439)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Caused by: java.lang.NullPointerException
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:469)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:424)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	... 12 more
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/Syntax/Flies Adapter.gaml
...........
Simulation duration: 8ms
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/Syntax/Flies.gaml
..............
Simulation duration: 160ms
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/Syntax/Mosquitos Adapter.gaml
...........
Simulation duration: 8ms
.Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Co-model Usage/Syntax/Mosquitos.gaml
.............
Simulation duration: 199ms
java.lang.NullPointerException
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:469)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:424)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Runtime error: Java error: nil value detected
Exception in thread "Thread-45" Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:63)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:439)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:413)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:356)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:264)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:112)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Caused by: java.lang.NullPointerException
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:469)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:424)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:57)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:80)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:107)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:237)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:242)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:287)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:206)
	at msi.gama.runtime.ExecutionScope.lambda$3(ExecutionScope.java:413)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	... 12 more
............
Simulation duration: 8493ms

**Comment by benoitgaudou** [comment]
Some others are due to the import of some particular file formats: 
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Data Importation/models/GEOJSON File Import.gaml
.java.lang.NullPointerException
Runtime error: Java error: nil value detected
	at msi.gama.util.GamaMapFactory.create(GamaMapFactory.java:73)
	at msi.gaml.operators.System.userInput(System.java:216)
	at gaml.additions.GamlAdditions$349.run(GamlAdditions.java:387)
	at gaml.additions.GamlAdditions$349.run(GamlAdditions.java:1)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:77)
	at msi.gama.runtime.ExecutionScope.lambda$5(ExecutionScope.java:420)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:420)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:448)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:379)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:359)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:107)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Exception in thread "Thread-59" Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:63)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:85)
	at msi.gama.runtime.ExecutionScope.lambda$5(ExecutionScope.java:420)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:420)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:448)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:379)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:359)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:107)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Caused by: java.lang.NullPointerException
	at msi.gama.util.GamaMapFactory.create(GamaMapFactory.java:73)
	at msi.gaml.operators.System.userInput(System.java:216)
	at gaml.additions.GamlAdditions$349.run(GamlAdditions.java:387)
	at gaml.additions.GamlAdditions$349.run(GamlAdditions.java:1)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:77)
	... 15 more
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Data Importation/models/GIS Export.gaml
......mars 01, 2017 11:45:59 AM org.geotools.data.shapefile.ShapefileDataStore createSchema
AVERTISSEMENT: PRJ file not generated for null CoordinateReferenceSystem
..........
Simulation duration: 296ms
.....
Simulation duration: 356ms
mars 01, 2017 11:46:01 AM org.geotools.coverage.grid.io.imageio.MaskOverviewProvider$SpiHelper <init>
AVERTISSEMENT: Unable to create a Reader for File: /Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Data Importation/includes/bogota_grid.tif
java.lang.IllegalArgumentException: input not a RandomAccessFile!
	at com.sun.imageio.spi.RAFImageInputStreamSpi.createInputStreamInstance(RAFImageInputStreamSpi.java:61)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider$SpiHelper.<init>(MaskOverviewProvider.java:720)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.<init>(MaskOverviewProvider.java:106)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.<init>(MaskOverviewProvider.java:101)
	at org.geotools.gce.geotiff.GeoTiffReader.getHRInfo(GeoTiffReader.java:357)
	at org.geotools.gce.geotiff.GeoTiffReader.<init>(GeoTiffReader.java:249)
	at msi.gama.util.file.GamaGridFile.getOwnCRS(GamaGridFile.java:382)
	at msi.gama.util.file.GamaGisFile.getExistingCRS(GamaGisFile.java:70)
	at msi.gama.util.file.GamaGridFile$GamaGridReader.<init>(GamaGridFile.java:148)
	at msi.gama.util.file.GamaGridFile.createReader(GamaGridFile.java:81)
	at msi.gama.util.file.GamaGridFile.fillBuffer(GamaGridFile.java:313)
	at msi.gama.util.file.GamaGridFile.computeEnvelope(GamaGridFile.java:298)
	at msi.gama.common.geometry.GeometryUtils.computeEnvelopeFrom(GeometryUtils.java:801)
	at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:1094)
	at gaml.additions.GamlAdditions$880.run(GamlAdditions.java:918)
	at gaml.additions.GamlAdditions$880.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:78)
	at msi.gama.runtime.ExecutionScope.lambda$5(ExecutionScope.java:420)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:420)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:448)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:379)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:359)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:107)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)

org.geotools.data.DataSourceException: java.lang.IllegalArgumentException: input not a RandomAccessFile!
	at org.geotools.gce.geotiff.GeoTiffReader.<init>(GeoTiffReader.java:262)
	at msi.gama.util.file.GamaGridFile.getOwnCRS(GamaGridFile.java:382)
	at msi.gama.util.file.GamaGisFile.getExistingCRS(GamaGisFile.java:70)
	at msi.gama.util.file.GamaGridFile$GamaGridReader.<init>(GamaGridFile.java:148)
	at msi.gama.util.file.GamaGridFile.createReader(GamaGridFile.java:81)
	at msi.gama.util.file.GamaGridFile.fillBuffer(GamaGridFile.java:313)
	at msi.gama.util.file.GamaGridFile.computeEnvelope(GamaGridFile.java:298)
	at msi.gama.common.geometry.GeometryUtils.computeEnvelopeFrom(GeometryUtils.java:801)
	at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:1094)
	at gaml.additions.GamlAdditions$880.run(GamlAdditions.java:918)
	at gaml.additions.GamlAdditions$880.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:78)
	at msi.gama.runtime.ExecutionScope.lambda$5(ExecutionScope.java:420)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:420)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:448)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:379)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:359)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:107)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Caused by: org.geotools.data.DataSourceException: java.lang.IllegalArgumentException: input not a RandomAccessFile!
	at org.geotools.gce.geotiff.GeoTiffReader.getHRInfo(GeoTiffReader.java:487)
	at org.geotools.gce.geotiff.GeoTiffReader.<init>(GeoTiffReader.java:249)
	... 26 more
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: input not a RandomAccessFile!
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider$SpiHelper.<init>(MaskOverviewProvider.java:729)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.<init>(MaskOverviewProvider.java:106)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.<init>(MaskOverviewProvider.java:101)
	at org.geotools.gce.geotiff.GeoTiffReader.getHRInfo(GeoTiffReader.java:357)
	... 27 more
Caused by: java.lang.IllegalArgumentException: input not a RandomAccessFile!
	at com.sun.imageio.spi.RAFImageInputStreamSpi.createInputStreamInstance(RAFImageInputStreamSpi.java:61)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider$SpiHelper.<init>(MaskOverviewProvider.java:720)
	... 30 more
mars 01, 2017 11:46:01 AM org.geotools.coverage.grid.io.imageio.MaskOverviewProvider$SpiHelper <init>
AVERTISSEMENT: Unable to create a Reader for File: /Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Data Importation/includes/bogota_grid.tif
java.lang.IllegalArgumentException: input not a RandomAccessFile!
	at com.sun.imageio.spi.RAFImageInputStreamSpi.createInputStreamInstance(RAFImageInputStreamSpi.java:61)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider$SpiHelper.<init>(MaskOverviewProvider.java:720)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.<init>(MaskOverviewProvider.java:106)
	at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.<init>(MaskOverviewProvider.java:101)
	at org.geotools.gce.geotiff.GeoTiffReader.getHRInfo(GeoTiffReader.java:357)
	at org.geotools.gce.geotiff.GeoTiffReader.<init>(GeoTiffReader.java:249)
	at msi.gama.util.file.GamaGridFile$GamaGridReader.<init>(GamaGridFile.java:153)
	at msi.gama.util.file.GamaGridFile.createReader(GamaGridFile.java:81)
	at msi.gama.util.file.GamaGridFile.fillBuffer(GamaGridFile.java:313)
	at msi.gama.util.file.GamaGridFile.computeEnvelope(GamaGridFile.java:298)
	at msi.gama.common.geometry.GeometryUtils.computeEnvelopeFrom(GeometryUtils.java:801)
	at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:1094)
	at gaml.additions.GamlAdditions$880.run(GamlAdditions.java:918)
	at gaml.additions.GamlAdditions$880.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:78)
	at msi.gama.runtime.ExecutionScope.lambda$5(ExecutionScope.java:420)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:420)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:448)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:379)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:359)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:107)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)

Exception in thread "Thread-57" The format of bogota_grid.tif is not correct. Error: The format of bogota_grid.tif is not correct. Error: java.lang.IllegalArgumentException: input not a RandomAccessFile!
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:67)
	at msi.gama.util.file.GamaGridFile.createReader(GamaGridFile.java:84)
	at msi.gama.util.file.GamaGridFile.fillBuffer(GamaGridFile.java:313)
	at msi.gama.util.file.GamaGridFile.computeEnvelope(GamaGridFile.java:298)
	at msi.gama.common.geometry.GeometryUtils.computeEnvelopeFrom(GeometryUtils.java:801)
	at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:1094)
	at gaml.additions.GamlAdditions$880.run(GamlAdditions.java:918)
	at gaml.additions.GamlAdditions$880.run(GamlAdditions.java:1)
	at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:78)
	at msi.gama.runtime.ExecutionScope.lambda$5(ExecutionScope.java:420)
	at msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:437)
	at msi.gama.runtime.ExecutionScope.pushRunAndCatch(ExecutionScope.java:428)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:420)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:448)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:379)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:359)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:107)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:92)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:284)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:145)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:75)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:69)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:215)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
mars 01, 2017 11:46:01 AM org.geotools.gce.arcgrid.ArcGridReader <init>
AVERTISSEMENT: Using default coordinate reference system 
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Data Importation/models/Grid DEM.gaml
.mars 01, 2017 11:46:01 AM org.geotools.gce.arcgrid.ArcGridReader <init>
AVERTISSEMENT: Using default coordinate reference system 
..........
Simulation duration: 167ms
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Data Importation/models/Grid DEM.gaml
.mars 01, 2017 11:46:02 AM org.geotools.gce.arcgrid.ArcGridReader <init>
AVERTISSEMENT: Using default coordinate reference system 
..........Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Data Importation/models/Grid DEM.gaml
.
Simulation duration: 346ms
Simulation is running...
from source file: //Users/bgaudou/Dev/wsEclipseMars/gama/msi.gama.models/models/Features/Data Importation/models/JSON File Import.gaml
...........
Simulation duration: 68ms
.Exception in thread "Thread-64" java.lang.RuntimeException: msi.gama.headless.core.GamaHeadlessException: Compilation errors: 
This definition of shape supersedes the one in built-in species agent
This definition of shape supersedes the one in built-in species agent
Cannot compile: msi.gama.lang.gaml.gaml.impl.FunctionImpl@4cbc2e3b (op: null)
'draw' cannot draw objects of type unknown

	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:88)
	at msi.gama.headless.runtime.LocalSimulationRuntime.loadModel(LocalSimulationRuntime.java:188)
	at msi.gama.headless.job.ExperimentJob.load(ExperimentJob.java:236)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:202)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Caused by: msi.gama.headless.core.GamaHeadlessException: Compilation errors: 
This definition of shape supersedes the one in built-in species agent
This definition of shape supersedes the one in built-in species agent
Cannot compile: msi.gama.lang.gaml.gaml.impl.FunctionImpl@4cbc2e3b (op: null)
'draw' cannot draw objects of type unknown

	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:80)
	... 4 more
.........
Simulation duration: 381ms
Exception in thread "Thread-65" java.lang.RuntimeException: msi.gama.headless.core.GamaHeadlessException: Compilation errors: 
This definition of shape supersedes the one in built-in species agent
This definition of shape supersedes the one in built-in species agent
Cannot compile: msi.gama.lang.gaml.gaml.impl.FunctionImpl@529c2a9a (op: null)

	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:88)
	at msi.gama.headless.runtime.LocalSimulationRuntime.loadModel(LocalSimulationRuntime.java:188)
	at msi.gama.headless.job.ExperimentJob.load(ExperimentJob.java:236)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:202)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:221)
Caused by: msi.gama.headless.core.GamaHeadlessException: Compilation errors: 
This definition of shape supersedes the one in built-in species agent
This definition of shape supersedes the one in built-in species agent
Cannot compile: msi.gama.lang.gaml.gaml.impl.FunctionImpl@529c2a9a (op: null)

	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:80)
	... 4 more

**Comment by AlexisDrogoul** [comment]
Coming back to this one. These are separate issues, I guess. The ones about the co-modeling need to investigated to see if it is not a simple path problem. @hqnghi88, have you taken a look at these errors in headless co-models ? Or @gnoubi ?

Regarding the second one, I'd bet that the correct libraries are not loaded by headless (in particular `json-simple` normally provided in `msi.gama.ext`). @gnoubi, would it be possible to take a look at this ? It has remained unanswered for quite a long time...

**Comment by gnoubi** [comment]
Hi 

Thanks for the reminder. I will look at this problem this week 

Nico

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by AlexisDrogoul** [comment]
Hi,

Related to #2259 (opened by @hqnghi88), what is the exact procedure to check/run all the models present in the workspace ? I'm a bit lost in the different indications provided in the previous comments. As I understand it, the headless run does not have any notion of a workspace (as the IDE is not loaded) so we have to pass it the path to the workspace. Ideally, we should have a unique command like: 

```
 sh gama-headless.sh -validate path_to_the_workspace_or_a_project path_to_an_output_file
```

that would return, in a new document, a list of all the warnings/errors found when recursively validating the different models found in the directory passed as an argument.

For running models, it should be the same (plus probably some options):

```
 sh gama-headless.sh -run path_to_the_workspace_or_a_project path_to_an_output_directory
```

where the different outputs (images, etc.) are saved (with meaningful names) to the output_directory.

Is something like this possible to have in a not so distant future ? Otherwise, if we have to fight with script shells, obscure options, cryptic xml files and so on,  nobody will ever work on automated validation... 

(btw, I am ready to develop this, as long as it doesn't interfere with other efforts from other developers).

**Comment by AlexisDrogoul** [comment]
Now tracked under #2453
