### ISSUE TITLE
Shader broken with some model 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2031]
### Steps to reproduce
1.Open Tutorials/Road Traffic/models/Model 01.gaml

2.use_shader:true

### Expected behavior
It should display the model.

### Actual behavior
The display is blank

Note some model work for example Built-In-Shapes.

It throws de following error:

Runtime error java.lang.Integer cannot be cast to msi.gama.util.GamaColor in OpenGL loop
java.lang.ClassCastException: java.lang.Integer cannot be cast to msi.gama.util.GamaColor

atummisco.gama.opengl.vaoGenerator.AbstractTransformer.getColorArray(AbstractTransformer.java:367)
at ummisco.gama.opengl.vaoGenerator.AbstractTransformer.getStandardDrawingEntities(AbstractTransformer.java:560)
at ummisco.gama.opengl.vaoGenerator.GeometryObjectTransformer.getDrawingEntityList(GeometryObjectTransformer.java:536)
at ummisco.gama.opengl.vaoGenerator.AbstractTransformer.getDrawingEntities(AbstractTransformer.java:478)
at ummisco.gama.opengl.vaoGenerator.DrawingEntityGenerator.GenerateDrawingEntities(DrawingEntityGenerator.java:153)
at ummisco.gama.opengl.vaoGenerator.DrawingEntityGenerator.GenerateDrawingEntities(DrawingEntityGenerator.java:35)
at ummisco.gama.opengl.scene.LayerObject.drawWithShader(LayerObject.java:126)
at ummisco.gama.opengl.scene.LayerObject.draw(LayerObject.java:98)
at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:180)
at ummisco.gama.opengl.ModernRenderer.drawScene(ModernRenderer.java:208)
at ummisco.gama.opengl.ModernRenderer.display(ModernRenderer.java:142)
at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
at ummisco.gama.opengl.SWTGLAnimator.displayGL(SWTGLAnimator.java:184)
at ummisco.gama.opengl.SWTGLAnimator.run(SWTGLAnimator.java:165)
at java.lang.Thread.run(Thread.java:745)

### System and version 
MAC OS - BUILD VERSION

**Comment by dphilippon** [comment]
I just committed something which seems to work fine now. Tell me if it is okay, so we can close the issue

**Comment by stouhbi** [comment]
The error persists. and now the erros are not viewed. Only an pop up dialog with the message NullPointerException

**Comment by agrignard** [comment]
Exactly the same behavior for me and I still have the error showing

**Comment by dphilippon** [comment]
@stouhbi I don't know where the null pointer exception could come from. Anyway, I've added different cases according to the type of the "colors" given (List, Color)... 
@agrignard do you think you can try it and tell me if it works for you ?

**Comment by agrignard** [comment]
still here for me

**Comment by agrignard** [comment]
OK it works now! well done @dphilippon
