### ISSUE TITLE
No Undo/Ctrl-Z/Redo on Ubuntu 16.04

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#2034]
### Steps to reproduce
- Open the latest version of Gama (git),  create a new workspace
- Open any model
- Edit any string/text/line
### Expected behavior

Using Ctrl-Z or Edit/Undo should cancel the edits.
### Actual behavior

No undo possible. Either via Ctrl-Z or with Edit/Undo (this remains greyed-out).
### Stupid fix

When launching an experiment and closing it, the Undo behavor goes back to normal.
But even with this, still no redo possible, which is hugely problematic in an editor.
### System and version
- Gama-dev,  git version : 1.7.0.201610251454
- Java version "1.8.0_111"
- Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
- Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
- Ubuntu 16.04 x64

**Comment by AlexisDrogoul** [comment]
Hi Robin,

Can you test (by downloading it) if this problem exists in the "official" release version of 1.7 ? You can find it here: https://github.com/gama-platform/gama/releases/download/v1.7/Gama1.7_Linux_64.zip

Thanks in advance,
Alexis

**Comment by AlexisDrogoul** [comment]
At first glance, it seems Eclipse/SWT have some stability and functionality problems with 16.04 (see for instance http://askubuntu.com/questions/761604/eclipse-not-working-in-16-04). No idea if it is related or not. 

Does this behavior happen at startup too ? i.e. when you have not launched any simulation yet ?

**Comment by RCura** [comment]
Just tested it. With this release version, I'm having exactly the same problem.
Can't undo until I open (and close) an experiment. This mean at startup of course, until I launch a simulation.

Here also, no redo even afterlauchung/relaunching experiment.

When I say opening experiment, I don't have to run any model, just go to the "simulation perspective" by choosing an experiment.

**Comment by AlexisDrogoul** [comment]
I've installed the same exact virtual machine as yours -- and I dont even know how you can launch GAMA. The whole is so plagued with errors and problems on Eclipse Mars that I havent been able to run GAMA from it on debug mode. On the web, the list is quite long, by the way, of people complaining about the stability of the OS regarding Java development. Only possibility I found was to downgrade to Ubuntu 14 -- where the problem doesn't exist. Eclipse Neon seems to behave a bit better, but we are not yet on our way to adopt it (other problems exist with it).

**Comment by RCura** [comment]
I built Gama using the `build.sh` script, which creates a release of Gama.
Didn't try using Eclipse.
Would the run log be usefull ?

**Comment by AlexisDrogoul** [comment]
Well, given that it is most probably due to SWT failing somewhere, I'm not sure it can show anything, but why not ?

**Comment by AlexisDrogoul** [comment]
As part of #1781, I've committed a new version that removes possible key bindings conflicts -- can you test if it solves your problem (I am skeptical, but who knows !) ?

**Comment by RCura** [comment]
Just tried (git pull & rebuild), this doesn't fix the problem.
And I can't paste a log, as nothing special appears on it, except many of those errors (with different ID each time):
> (Gama Platform:15044): GLib-CRITICAL **: Source ID 12579 was not found when attempting to remove it

But it's usual, and doesn't concern (I think) this problem.

**Comment by RCura** [comment]
Just looking at this old issue : since GTK problems have been handled with Ubuntu, this bug isn't valid anymore : I can Undo/Redo and so on on Gama 1.7 git version
