### ISSUE TITLE
GAMA release and Sierra (App is Damaged Can’t Be Opened)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2082]
### Steps to reproduce
1. Download the last release of GAMA (continuously built)

2. Try to run it with Sierra (Mac OS X)

### Expected behavior
GAMA should run normally

### Actual behavior
get a message : App is Damaged Can’t Be Opened.... 
the only solution that I found to make it work is to disable the gatekeeper (sudo spctl --master-disable) to be able to choose the "anywhere" option in the security panel... 
not really a good solution.

### System and version 
Mac OS X Sierra, Release version of GAMA

**Comment by sriramab** [comment]
I had no problems with Sierra. I just had to say "open anyway" to the risk warning by mac.

however, strangely, in gama course yesterday, one student could not install gama at all. he just sat throughout the course :(

**Comment by AlexisDrogoul** [comment]
Never had this problem myself. Have you tried the workaround specified in https://bugs.eclipse.org/bugs/show_bug.cgi?id=398450#c17 ?

**Comment by ptaillandier** [comment]
The solution proposed by Alexis seems to work. We should add a note in the documentation about this problem.

**Comment by AlexisDrogoul** [comment]
Done (https://github.com/gama-platform/gama/wiki/Installation#macos)

**Comment by sriramab** [comment]
This is still a problem even with your suggested methods. I downloaded the new build yesterday and then again today, and quite a few times, but... this error continues even with stuff expander. Should I be changing some settings in stuff expander?

**Comment by sriramab** [comment]
the bugs link worked for me
