### ISSUE TITLE
Opengl CoordinateArray Sequence strange behavior

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2090]
### Steps to reproduce
A bit hard to reproduce as it depends on GIS data but I had a model that worked few weeks ago and that crashes now. 

### Expected behavior
It used to work in term of display with only a warning
at cycle 0: GamaShapeFile.fillBuffer; geometry could not be added  as it is empty: buildings.117

### Actual behavior
I still have the warning but it also raise an error and make the display freezing with the following error message

Runtime error com.vividsolutions.jts.geom.impl.CoordinateArraySequence cannot be cast to msi.gama.common.util.GeometryUtils$GamaCoordinateSequence in OpenGL loop
java.lang.ClassCastException: com.vividsolutions.jts.geom.impl.CoordinateArraySequence cannot be cast to msi.gama.common.util.GeometryUtils$GamaCoordinateSequence
	at msi.gama.common.util.GeometryUtils.getCoordinates(GeometryUtils.java:1191)
	at ummisco.gama.opengl.jts.JTSDrawer.drawTesselatedPolygon(JTSDrawer.java:153)
	at ummisco.gama.opengl.jts.JTSDrawer.drawPolygon(JTSDrawer.java:119)
	at ummisco.gama.opengl.jts.JTSDrawer.drawPolyhedre(JTSDrawer.java:242)
	at ummisco.gama.opengl.scene.GeometryDrawer._draw(GeometryDrawer.java:95)
	at ummisco.gama.opengl.scene.GeometryDrawer._draw(GeometryDrawer.java:1)
	at ummisco.gama.opengl.scene.ObjectDrawer.draw(ObjectDrawer.java:33)
	at ummisco.gama.opengl.scene.AbstractObject.draw(AbstractObject.java:160)
	at ummisco.gama.opengl.scene.LayerObject.drawWithoutShader(LayerObject.java:187)
	at ummisco.gama.opengl.scene.LayerObject.draw(LayerObject.java:99)
	at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:179)
	at ummisco.gama.opengl.JOGLRenderer.drawScene(JOGLRenderer.java:290)
	at ummisco.gama.opengl.JOGLRenderer.display(JOGLRenderer.java:203)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
	at ummisco.gama.opengl.SWTGLAnimator.displayGL(SWTGLAnimator.java:194)
	at ummisco.gama.opengl.SWTGLAnimator.run(SWTGLAnimator.java:175)
	at java.lang.Thread.run(Thread.java:745)

### System and version 
GIT version

**Comment by AlexisDrogoul** [comment]
Do you have the GIS data at hand. Normally, this error has been corrected, but it's preferable to test it with the "bad" data (provoking the warning) you are using.

**Comment by agrignard** [comment]
[Andorra.zip](https://github.com/gama-platform/gama/files/709733/Andorra.zip)

I still have the problem. For sure it come from the GIS file (that I did not control and that was made "by hand") but it used to work like one month ago. There is one specific building that gives a problem. 

Run AndorraABM.gaml and Display Experiment

Note 1: No problem to open this GIS in QGIS
Note 2:  Please don't share those data

**Comment by AlexisDrogoul** [comment]
Since the data was not supposed to be shared, putting it on a GitHub account was not a good idea :)
I deleted it. I have tried it and it works now on my working version. I obtain this kind of output:

![multipleview - users drogoul documents programmation gama_workspacerelease572 andorra models andorrabm gaml 2017-01-17 08-10-42](https://cloud.githubusercontent.com/assets/579256/22004217/8b1532e0-dc8c-11e6-9a89-4a070aebc411.png)

Is it correct ? 

Cheers
Alexis

**Comment by agrignard** [comment]
Yep it should be "more or less" what you should see.

However on my version (I am up to date with the GIT)

I have this error:

java.lang.ClassCastException:
com.vividsolutions.jts.geom.impl.CoordinateArraySequence cannot be cast to
msi.gama.common.util.GeometryUtils$GamaCoordinateSequence
    at
msi.gama.common.util.GeometryUtils.getCoordinates(GeometryUtils.java:1191)
    at
ummisco.gama.opengl.jts.JTSDrawer.drawTesselatedPolygon(JTSDrawer.java:153)
    at ummisco.gama.opengl.jts.JTSDrawer.drawPolygon(JTSDrawer.java:119)
    at
ummisco.gama.opengl.scene.GeometryDrawer._draw(GeometryDrawer.java:98)
    at ummisco.gama.opengl.scene.GeometryDrawer._draw(GeometryDrawer.java:1)
    at ummisco.gama.opengl.scene.ObjectDrawer.draw(ObjectDrawer.java:33)
    at
ummisco.gama.opengl.scene.AbstractObject.draw(AbstractObject.java:160)
    at
ummisco.gama.opengl.scene.LayerObject.drawWithoutShader(LayerObject.java:187)
    at ummisco.gama.opengl.scene.LayerObject.draw(LayerObject.java:99)
    at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:179)
    at ummisco.gama.opengl.JOGLRenderer.drawScene(JOGLRenderer.java:290)
    at ummisco.gama.opengl.JOGLRenderer.display(JOGLRenderer.java:203)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
    at
jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
    at ummisco.gama.opengl.SWTGLAnimator.displayGL(SWTGLAnimator.java:194)
    at ummisco.gama.opengl.SWTGLAnimator.run(SWTGLAnimator.java:175)
    at java.lang.Thread.run(Thread.java:745)

**Comment by agrignard** [comment]
Just for information I am in a hackaton at dentsu in Tokyo trying to
implement a short demo on GAMA with railways and roads and I get the same
problem with another shapefile that is supposed to be a clean one. It is a
shapefile of the Japan taken from here
http://www.diva-gis.org/gdata

It is working on the latest build but not on the current GIT version.

**Comment by AlexisDrogoul** [comment]
This problem has been corrected. However, in the original shape file provided, I have detected at least 25 problems in the geometries of buildings. Some are empty (caught by the shape file reader), some are self-crossing (not caught and leading to errors in OpenGL rendering, for example when computing normals). I am right now trying to catch these problems in the coordinate sequences.

**Comment by agrignard** [comment]
Great. 

I know that the original data is very bad (more or less made by hand by different people (I  am actually fighting with them to produce cleaner data)). Actually I don't want you to spend so much time on this specific dataset but I think that it is important to be able to at least display the file. In a  software like QGIS there is no problem to open those file which means that at some point QGIS is also taking care about those specific problem and GAMA should do at least the same.

**Comment by AlexisDrogoul** [comment]
I agree. And it is already the case.  I've tried to devise automated ways for "correcting" the original data (removal of duplicate points, empty vertices, etc.), but the number of specific cases is too large. So Ill leave the geometries untouched, knowing that they sometimes produce strange effects (for instance, a reversed building displayed in 3D, pointing to the bottom).

**Comment by AlexisDrogoul** [comment]
Fixed by 2553eb21926cfc83603888c96ce2c602b088f3c6
