### ISSUE TITLE
Markdown documentation does not work

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#3044]
Hi

There is an extension "Markdown Documentation" in experimental plugins, that would enlist all the variables in a model and in the experiment. It used to work until 2019, but now seems not to be working. Could you please revive this if possible. The plugin installs the item in the context menu, but does not produce the documentation as expected.

Thank you
Srirama

**Comment by benoitgaudou** [comment]
Hi Srirama,
I just committed a  small fix. I  tried  it and it generates  again a markdown file, I let you check whether it contains what you were  expecting.
Cheers

Benoit

**Comment by sriramab** [comment]
excellent. thank you Benoit. It works like before. Unfortunately for now, it missed the bus on my new video.

**Comment by sriramab** [comment]
Hi Benoit, Please see the path of the new file is not same as the new folder created. May you forgot to place it in the new folder in the parent folder. the markdown file is created in the current folder instead.

**Comment by benoitgaudou** [comment]
Hi Srirama,

I am not sure to understand your point.
When I create a new project, with a model and  that I  ask to build  the Markdown (in the includes forlder) I  get the following files.

<img width="295" alt="Screenshot 2020-11-06 at 21 45 49" src="https://user-images.githubusercontent.com/1555274/98413203-8043f100-2079-11eb-8e9a-7f5af9eb5018.png">

Could be more precise on what  you  are expecting ?

**Comment by sriramab** [comment]
Hi Benoit,

If you do not specify a particular output folder, that is, if you just accept the default folder suggestion the first time you click "markdown documentation"..... it does not place the files correctly as you see in the image below:

It creates a folder in the parent folder, but create the markdown file in the current folder.

![image](https://user-images.githubusercontent.com/12668606/98434286-a647b080-20ce-11eb-8c29-8d1ab1cb1421.png)

**Comment by benoitgaudou** [comment]
Hi Srirama,
I do not agree with you on the fact that filess  are not correctly located:
when you click on "Generate  Markdown  Documentation", a window appears
and ask you  the  folder where  you want to write the  markdown files.
The default choice is the folder "model", i.e. the same location as the
model.
So if you do not modify this choice, the .md files wil be in the models
folder, the same place as your model.
I think we have to let the user choose the location for  the md files ...

Cheers

Benoit

**Comment by sriramab** [comment]
Hi Benoit, 

Please see, I tried again.  Below in the attached figure, you will see 3 times the folder structure. 

1 )  No use of "generate markdown documentation" (0 folders, 6 files) 
2) Use of "generate markdown documentation", but with no user modification on output folder ( 2 folders, 9 files)
3) Use of "generate markdown documentation" and user selected folder.  (3 folders, 9 files) 

Please close the issue, if this is not the case in your computer. 


![image](https://user-images.githubusercontent.com/12668606/98444262-f9425780-2110-11eb-8925-644311712397.png)

**Comment by benoitgaudou** [comment]
Hi  Srirama,
I have the same as you, but do not see the issue.

If I can rename your 2 cases, it would  be:

2) Use of "generate markdown documentation", and *user selects the folder
'models'* as output folder ( in '*models' folder* I have  Index.md and
model1.md and the folder Lunary Flu with models/model1.md inside)
3) Use of "generate markdown documentation" and* user selects the folder
'userFolder*' as output folder. ( in '*userFolder' folder* I have  Index.md
and model1.md and the folder Lunary Flu with models/model1.md inside)
They seem perfectly coherent to me.

Cheers

Benoit

**Comment by sriramab** [comment]
So the extension is meant to create  the markdown file **twice**, one inside and one outside ?

**Comment by benoitgaudou** [comment]
On the question of what is generated, I admit that I admit I did not pay so
much attention on that point for the moment.
But generating the md files on another project with more files, it seems
that we do not have a file twice...

Nevertheless, the extension needs some improvements in
particular concerning the file at the same level than Index.md

We can open an issue on this specific point, but not sure I will have time
to dig in depth in the markdown extension for the moment ...

[image: Screenshot 2020-11-07 at 16.51.47.png]

**Comment by sriramab** [comment]
Thank you. It at least works now. Just seems like a minor glitch. I close this issue for now. Thank you
