### ISSUE TITLE
Add text with links in the parameter window

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#604]
Currently, it is possible to add text in the parameter window. This can be helpful to explain the different parameters, and more generally, how the model works. However some models may refer to webpages, either in the Gama documentation or from external websites (wikipedia ?).

**Describe the improvement you'd like**
Enhance 'text' or add a 'link' statement that will display a text, with a clickable link to a given url, such as

````
urlLink message: "click here" url: "www.gama.com" color: #yellow category: "Help";
````

Here is an example of how it would look:

![Image](https://github.com/user-attachments/assets/630164fc-8139-4f38-a3b4-81250ebf71b2)

**Comment by AlexisDrogoul** [comment]
I think it would be much easier to detect the links in the texts.

**Comment by tnguyenh** [comment]
I'm ok with that solution. On the other hand, having a specific statement allow to display different from the link (useful to write "click here" when you have a very long url).

**Comment by AlexisDrogoul** [comment]
`text` now accepts an additional facet, `format`, that, when set to `true`, interprets the URLs and a few XML tags within the text to provide hyperlinks and some formatting (bullet lists, paragraphs, etc.)

**Comment by tnguyenh** [comment]
So now the appearance of the text is great, but there is an issue with the tags. Badly nested tags prevent any display in the paremeter window.

````
text "Bonjour le monde" format: true;
text "Hello <p> world</p>" format: true;
````
works great:

![Image](https://github.com/user-attachments/assets/ea48468c-7f9a-4a8a-a4e6-f0275fbc4753)

but
````
text "Bonjour le monde" format: true;
text "Hello <p> world" format: true;
````
doesn't work.
![Image](https://github.com/user-attachments/assets/ea54824a-d192-47fa-9f33-1ac079e098ce)

Besides, <br> don't work at all: with just <br>, everything is removed from the parameter window, and if you try something like <br></br> the part within the tags is removed.

**Comment by tnguyenh** [comment]
Now it is broken. Using text results in an swt error, with the text completely disappearing from the editor.

![Image](https://github.com/user-attachments/assets/63d42243-86f3-48ff-9cfb-43e438d0516e)

Note that I have the following error when starting Gama from Eclipse. I have no idea if it can be related, so I mention it here:

![Image](https://github.com/user-attachments/assets/18abe4d5-e6a2-471b-a20c-4a1e8f94a783)

**Comment by AlexisDrogoul** [comment]
Should be mostly fixed with the latest version.

**Comment by AlexisDrogoul** [comment]
Please close once tested.

**Comment by tnguyenh** [comment]
It's better, I don't have the SWT error anymore. The documentation is still the same, with parts missing, and the blue link that makes Gama freeze.

I don't knwo which tag are usable since the documentation has missing part, so I cannot fully test it.
